### ISSUE TITLE
Errors when running on MacOS M1 machine

### ISSUE THREAD

**Issue by tording** [MaxBroome/UniFiAuto-Inform#1]
I tried running this on my M1 Mac using the python 3 interpreter.   I am getting the following errors.   

<img width="1152" alt="Screenshot 2023-05-26 at 8 11 00 AM" src="https://github.com/MaxBroome/UniFiAuto-Inform/assets/30204490/04665154-6789-4ac4-9c0c-5ddbb8080161">

**Comment by MaxBroome** [comment]
Fixed in the new update! Moved from arp -a (a Windows specific command) to nmap!
