### ISSUE TITLE
Trying this out on an M1 Mac... 

### ISSUE THREAD

**Issue by markengelhardt** [MaxBroome/UniFiAuto-Inform#2]
The MacOS steps I used are as follows:

Download and Install nmap  from https://nmap.org via the .dmg installer they provide
pip install paramiko
pip install python-nmap    _instead of pip install nmap_ 
sudo python UniFi\ Device\ Discovery\ and\ Inform\ Tool.py

These steps worked for me on an M1 mac, but I did not try and change any devices.

**Comment by MaxBroome** [comment]
I'm not quite sure what your issue is here... 

> but I did not try and change any devices.

Do you mean the script will not inform all the devices?

**Comment by MaxBroome** [comment]
Closing this issue due to lack of information and activity,

**Comment by MaxBroome** [comment]
Closing this issue due to lack of information and activity,

**Comment by markengelhardt** [comment]
Sorry I was not clear, I think you just need to change the read me to show you need python-nmap instead of just nmap when you are on a mac

**Comment by MaxBroome** [comment]
ah I see, thank you. I will correct the documentation!
