### ISSUE TITLE
Option to specify port

### ISSUE THREAD

**Issue by wrench12435678** [MaxBroome/UniFiAuto-Inform#3]
Ask if you want to use default port or not

Or for the url add an option for the user to give it the exact url

**Comment by MaxBroome** [comment]
Sorry for the late reply. As in the port the UniFi controller is listening for devices on?

**Comment by wrench12435678** [comment]
Yeah so by default the script is 8080, either a config file where you can change variables (so updating wouldn't overwrite changes) or as a prompt to ask :)

**Comment by MaxBroome** [comment]
I will add this feature in the coming Electron app release! :wink:
